In [86]:
import pandas as pd
import numpy as np


In [87]:
correc_df = pd.read_csv('tabla_correccion.csv')
tabla = correc_df.values

print (tabla)

[[-2  2  0 -1  1]
 [-1  1 -2  2  0]
 [ 2  0 -1  1 -2]
 [ 1 -2  2  0 -1]
 [ 0 -1  1 -2  2]
 [-2  2  0 -1  1]
 [ 0 -1  1 -2  2]
 [-2  2  0 -1  1]
 [ 2  0 -1  1 -2]
 [ 1 -2  2  0 -1]
 [ 1 -2  2  0 -1]
 [ 0 -1  1 -2  2]
 [-2  2  0 -1  1]
 [-1  1 -2  2  0]
 [ 2  0 -1  1 -2]
 [ 1 -2  2  0 -1]
 [ 0 -1  1 -2  2]
 [-2  2  0 -1  1]
 [-1  1 -2  2  0]
 [ 2  0 -1  1 -2]
 [ 1 -2  2  0 -1]
 [-2  2  0 -1  1]
 [-2  2  0 -1  1]
 [ 0 -1  1 -2  2]
 [-1  1 -2  2  0]
 [ 2  0 -1  1 -2]
 [ 1 -2  2  0 -1]]


In [88]:

sujetos = pd.read_csv('tabla_resultados.csv')
sujetos.head()




Suje1 Suje2 Suje3 Suje4
0     A     B     A     A
1     A     B     A     C
2     A     B     B     C
3     A     B     A     B
4     A     B     E     B

In [89]:
percentil = pd.read_csv('tabla_percentil.csv')
percentil.tail()

percentil  agresivoV  agresivoM  controlV  controlM  pasivoV  pasivoM
6          60          9          7        18        20        6        3
7          70         13          9        19        21        9        4
8          80         16         10        21        21       11        6
9          90         18         15        22        23       13        9
10         99         29         23        25        25       21       13

In [90]:

percentil = pd.read_csv('tabla_percentil.csv')
percentil.head()
percentil_v = pd.read_csv('tabla_percentil_varon.csv')
percentil_v.tail()

percentil  agresivoV  controlV  pasivoV
7          70         13        19        9
8          80         16        21       11
9          90         18        22       13
10         99         29        25       21
11        100        100       100      100

In [91]:
contador = 0
suj1 = []
for items in sujetos.Sujeto3:

    match (items):
        case "A":
            suj1.append (tabla[contador][0])  
        case "B":
            suj1.append(tabla[contador][1])
        case "C":
            suj1.append(tabla[contador][2])
        case "D":
            suj1.append(tabla[contador][3])
        case "E":
            suj1.append(tabla[contador][4])
    contador += 1
suj1
print(len(suj1))

AttributeError: 'DataFrame' object has no attribute 'Sujeto3'

In [ ]:
contador = 0
suj1 = np.array
for items in sujetos.Sujeto2:
    #if  (items == "B" ) :
        #print (tabla[contador][1])
    contador += 1

#print(len(tabla))

AttributeError: 'DataFrame' object has no attribute 'Sujeto2'

In [ ]:
for column in sujetos.columns[1:3]:
    print(sujetos[column])

0     B
1     B
2     B
3     B
4     B
5     B
6     B
7     B
8     B
9     B
10    B
11    B
12    B
13    B
14    B
15    B
16    B
17    B
18    B
19    B
20    B
21    B
22    B
23    B
24    B
25    B
26    B
Name: Suje2, dtype: object
0     A
1     A
2     B
3     A
4     E
5     A
6     D
7     C
8     A
9     D
10    D
11    A
12    C
13    B
14    A
15    E
16    A
17    C
18    A
19    E
20    D
21    A
22    C
23    A
24    A
25    E
26    B
Name: Suje3, dtype: object


In [ ]:
columna = 0
suj = []
lista = []
numerico = pd.DataFrame(columns=sujetos.columns)
print(numerico)

for column in sujetos.columns[:]:
 
    fila = 0
    for items in sujetos[column]:
        
        #print (items)
        match (items):
            case "A":
              lista.append (tabla[fila][0])  
            case "B":
              lista.append(tabla[fila][1])
            case "C":
               lista.append(tabla[fila][2])
            case "D":
               lista.append(tabla[fila][3])
            case "E":
              lista.append(tabla[fila][4])

        fila +=1
    #print (lista)

    numerico[column] = lista
    se = pd.Series(lista)
   
    lista.clear()
    columna += 1
numerico.head()



Empty DataFrame
Columns: [Suje1, Suje2, Suje3, Suje4]
Index: []


Suje1  Suje2  Suje3  Suje4
0     -2      2     -2     -2
1     -1      1     -1     -2
2      2      0      0     -1
3      1     -2      1     -2
4      0     -1      2     -1

In [ ]:
clasificado = pd.DataFrame(columns=sujetos.columns)


for column in numerico.columns[:]:
    asertivo=0
    pasivo=0
    agresivo=0
    fila = 0
    for items in numerico[column]:
        if items == 0:
            asertivo +=1
        elif items >0 :
            agresivo = agresivo + items
        else :
            pasivo -= items
    clasificado[column] = [asertivo,pasivo,agresivo]
print (clasificado)



#clasificado.loc[len(clasificado)] = [:]

   Suje1  Suje2  Suje3  Suje4
0      5      5     11      9
1     18     17     18     22
2     16     18      8      0


In [ ]:
percentil_v.head()

percentil  agresivoV  controlV  pasivoV
0          1          0         4        0
1         10          2         7        1
2         20          4        10        1
3         30          5        12        2
4         40          6        13        3

In [ ]:
porciento = pd.DataFrame(columns=sujetos.columns)




#print (percentil_v.pasivoV[7])
print(percentil_v.loc[percentil_v["agresivoV"] == 3])


Empty DataFrame
Columns: [percentil, agresivoV, controlV, pasivoV]
Index: []


In [ ]:
for i,fil in clasificado.iterrows():
    print ("fila" ,i ,fil*2)
    if i = 0 :
        print (percentil_v[pasivoV][fil])

In [ ]:
# La tabla de percentiles
tabla_percentiles = {
    'percentil': [1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 99,100],
    'agresivoV': [0, 2, 4, 5, 6, 7, 9, 13, 16, 18, 29,100],
    'controlV': [4, 7, 10, 12, 13, 15, 18, 19, 21, 22, 25,100],
    'pasivoV': [0, 1, 1, 2, 3, 4, 6, 9, 11, 13, 21, 100]
}

df_percentiles = pd.DataFrame(tabla_percentiles)

df_percentiles.head()

percentil  agresivoV  controlV  pasivoV
0          1          0         4        0
1         10          2         7        1
2         20          4        10        1
3         30          5        12        2
4         40          6        13        3

In [109]:


# Tu DataFrame de resultados de la encuesta
data = {
    'Suje1': [5, 18, 16],
    'Suje2': [5, 17, 18],
    'Suje3': [11, 18, 8],
    'Suje4': [9, 22, 0]
}
df_encuesta = pd.DataFrame(data)
df_encuesta.head()


Suje1  Suje2  Suje3  Suje4
0      5      5     11      9
1     18     17     18     22
2     16     18      8      0

In [116]:
data = {
    'Suje1': [[5, 18, 16]],
    'Suje2': [[5, 17, 18]],
    'Suje3': [[11, 18, 8]],
    'Suje4': [[9, 22, 0]]
}
df_encuesta = pd.DataFrame(data)
df_encuesta.head()

Suje1        Suje2        Suje3       Suje4
0  [5, 18, 16]  [5, 17, 18]  [11, 18, 8]  [9, 22, 0]

Suje1  Suje2  Suje3  Suje4
0      5      5     11      9
1     18     17     18     22
2     16     18      8      0

In [131]:

# Función para calcular el percentil correspondiente
#def calcular_percentil(valor, tipo_comportamiento):
 #   percentil = df_percentiles[df_percentiles[tipo_comportamiento] >= valor][tipo_comportamiento].iloc[0]
 #   return percentil if percentil is not None else 100

In [134]:
# Función para calcular el percentil correspondiente
def calcular_percentil(valor, tipo_comportamiento):
    percentil = df_percentiles[df_percentiles[tipo_comportamiento] >= valor]['percentil'].min()
    return percentil if percentil is not None else 100


In [135]:
calcular_percentil(5, 'agresivoV')

30

In [103]:




# Calcular percentiles para cada sujeto en el DataFrame de la encuesta
for col in df_encuesta.columns:
    for index, valor in df_encuesta[col].items():
        agresivo_percentil = calcular_percentil(valor, 'agresivoV')
        control_percentil = calcular_percentil(valor, 'controlV')
        pasivo_percentil = calcular_percentil(valor, 'pasivoV')
        print(f"Sujeto: {col}, Valor: {valor}, Percentil Agresivo: {agresivo_percentil}, Percentil Control: {control_percentil}, Percentil Pasivo: {pasivo_percentil}")

Sujeto: Suje1, Valor: 5, Percentil Agresivo: 30, Percentil Control: 10, Percentil Pasivo: 60
Sujeto: Suje1, Valor: 18, Percentil Agresivo: 90, Percentil Control: 60, Percentil Pasivo: 99
Sujeto: Suje1, Valor: 16, Percentil Agresivo: 80, Percentil Control: 60, Percentil Pasivo: 99
Sujeto: Suje2, Valor: 5, Percentil Agresivo: 30, Percentil Control: 10, Percentil Pasivo: 60
Sujeto: Suje2, Valor: 17, Percentil Agresivo: 90, Percentil Control: 60, Percentil Pasivo: 99
Sujeto: Suje2, Valor: 18, Percentil Agresivo: 90, Percentil Control: 60, Percentil Pasivo: 99
Sujeto: Suje3, Valor: 11, Percentil Agresivo: 70, Percentil Control: 30, Percentil Pasivo: 80
Sujeto: Suje3, Valor: 18, Percentil Agresivo: 90, Percentil Control: 60, Percentil Pasivo: 99
Sujeto: Suje3, Valor: 8, Percentil Agresivo: 60, Percentil Control: 20, Percentil Pasivo: 70
Sujeto: Suje4, Valor: 9, Percentil Agresivo: 60, Percentil Control: 20, Percentil Pasivo: 70
Sujeto: Suje4, Valor: 22, Percentil Agresivo: 99, Percentil Cont

In [123]:
# Calcular percentiles para cada sujeto en el DataFrame de la encuesta
for col in df_encuesta.columns:
    for index, valores in df_encuesta[col].items():
        control_percentil = calcular_percentil(valores[0], 'controlV')
        pasivo_percentil = calcular_percentil(valores[1], 'pasivoV')
        agresivo_percentil = calcular_percentil(valores[2], 'agresivoV')
        print(f"Sujeto: {col}, Valor Control: {valores[0]}, Percentil Control: {control_percentil}")
        print(f"Sujeto: {col}, Valor Pasivo: {valores[1]}, Percentil Pasivo: {pasivo_percentil}")
        print(f"Sujeto: {col}, Valor Agresivo: {valores[2]}, Percentil Agresivo: {agresivo_percentil}")

Sujeto: Suje1, Valor Control: 5, Percentil Control: 10
Sujeto: Suje1, Valor Pasivo: 18, Percentil Pasivo: 99
Sujeto: Suje1, Valor Agresivo: 16, Percentil Agresivo: 80
Sujeto: Suje2, Valor Control: 5, Percentil Control: 10
Sujeto: Suje2, Valor Pasivo: 17, Percentil Pasivo: 99
Sujeto: Suje2, Valor Agresivo: 18, Percentil Agresivo: 90
Sujeto: Suje3, Valor Control: 11, Percentil Control: 30
Sujeto: Suje3, Valor Pasivo: 18, Percentil Pasivo: 99
Sujeto: Suje3, Valor Agresivo: 8, Percentil Agresivo: 60
Sujeto: Suje4, Valor Control: 9, Percentil Control: 20
Sujeto: Suje4, Valor Pasivo: 22, Percentil Pasivo: 100
Sujeto: Suje4, Valor Agresivo: 0, Percentil Agresivo: 1


In [124]:

# Lista para almacenar los resultados de cada sujeto
resultados = []

# Calcular percentiles para cada sujeto en el DataFrame de la encuesta
for col in df_encuesta.columns:
    for index, valores in df_encuesta[col].items():
        control_percentil = calcular_percentil(valores[0], 'controlV')
        pasivo_percentil = calcular_percentil(valores[1], 'pasivoV')
        agresivo_percentil = calcular_percentil(valores[2], 'agresivoV')
        
        # Guardar los resultados en un diccionario
        resultados.append({
            'Sujeto': col,
            'Valor Control': valores[0],
            'Percentil Control': control_percentil,
            'Valor Pasivo': valores[1],
            'Percentil Pasivo': pasivo_percentil,
            'Valor Agresivo': valores[2],
            'Percentil Agresivo': agresivo_percentil
        })

# Convertir la lista de resultados en un DataFrame
df_resultados = pd.DataFrame(resultados)

# Mostrar el DataFrame con los resultados
print(df_resultados)

  Sujeto  Valor Control  Percentil Control  Valor Pasivo  Percentil Pasivo  \
0  Suje1              5                 10            18                99   
1  Suje2              5                 10            17                99   
2  Suje3             11                 30            18                99   
3  Suje4              9                 20            22               100   

   Valor Agresivo  Percentil Agresivo  
0              16                  80  
1              18                  90  
2               8                  60  
3               0                   1  
